### ISSUE TITLE
bounding box -TypeError: 'dict' object is not callable

### ISSUE THREAD

**Issue by johnyquest7** [turner-anderson/streamlit-cropper#4]
When I tried to pass a bounding box function to cropper - it threw an error. TypeError: 'dict' object is not callable

Full error
File "/home/quest/anaconda3/envs/fastaiv2_2020_nov/lib/python3.8/site-packages/streamlit_cropper/__init__.py", line 116, in st_cropper
    box = box_algorithm(img, aspect_ratio=aspect_ratio)

Full code

`import streamlit as st
from streamlit_cropper import st_cropper
from PIL import Image
st.set_option('deprecation.showfileUploaderEncoding', False)
val=100

st.header("Cropper Demo")
img_file = st.sidebar.file_uploader(label='Upload a file', type=['png', 'jpg','PNG', 'JPG',"TIFF", "TIF"])
#realtime_update = st.sidebar.checkbox(label="Update in Real Time", value=True)
realtime_update = False
#box_color = st.sidebar.color_picker(label="Box Color", value='#FF001B')
box_color = '#FF001B'
#aspect_choice = st.sidebar.radio(label="Aspect Ratio", options=["1:1", "16:9", "4:3", "2:3", "Free"])
aspect_dict = {"1:1": (1,1),
                "16:9": (16,9),
                "4:3": (4,3),
                "2:3": (2,3),
                "Free": None}
aspect_ratio = aspect_dict["1:1"]

def return_box(img):
    box = {"left": 0, "top":0, "width":100, "height":100}
    return box

if img_file:
    img = Image.open(img_file)
    if not realtime_update:
        st.write("Double click to save crop")
    # Get a cropped image from the frontend
    cropped_img = st_cropper(img, realtime_update=realtime_update, box_color=box_color,box_algorithm =return_box(img),
                                aspect_ratio=aspect_ratio)

    # Manipulate cropped image at will
    #st.write("Preview")
    #_ = cropped_img.thumbnail((150,150))
    st.image(cropped_img)
`

**Comment by turner-anderson** [comment]
So the cropper is actually expecting the function itself as an argument rather than the dictionary returned by the function. In this case, you'd want to change the final line to:

```
cropped_img = st_cropper(img, realtime_update=realtime_update, box_color=box_color,box_algorithm =return_box,
aspect_ratio=aspect_ratio)
```
And then it's expecting the return_box function to at least accept an aspect_ratio argument so you'd need to update the function to something like this:

```
def return_box(img, aspect_ratio=None):
  box = {"left": 0, "top":0, "width":100, "height":100}
  return box
```

I'll try to push an update in the next few days that checks for the type on what's passed in there and give a little clearer error message, and also defaults the aspect_ratio to either 1:1 or free whenever the user-defined box function does not accept an aspect_ratio argument.

Let me know if that makes sense.

**Comment by johnyquest7** [comment]
Thanks. Your solution worked perfectly! 
I am using square aspect ratio for all my images.
